apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  namespace: development
  labels:
    app: jekyll
    run: jekyll
spec:
  containers:
  - name: jekyll
    image: kodekloud/jekyll-serve
    volumeMounts:
    - name: site
      mountPath: "/site"
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: 'jekyll-site'
  initContainers:
  - name: 'copy-jekyll-site'
    image: kodekloud/jekyll
    command: [ "jekyll", "new", "/site" ]
    volumeMounts:
    - name: site
      mountPath: "/site"
  volumes:
  - name: site
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  type: NodePort
  selector:
    app: jekyll
    run: jekyll
  ports:
    - port: 8080
      targetPort: 4000
      nodePort: 30097
~                                                                                                                                                                                                        
~                                                                                                                                                                                                        
~                                                                                                                                                                                                        
~                                                                                                                                                                                                        
"pod.yaml" 44L, 774C