apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
  labels:
    app: drupal-mysql
spec:
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
           containerPort: 3306
           name: mysql
           protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-secret
              key: MYSQL_USER
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: vol-drupal
          mountPath: /var/lib/mysql
      volumes:
      - name: vol-drupal
        persistentVolumeClaim:
          claimName: drupal-mysql-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql
  labels:
    app: drupal
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: drupal
